# Generated by Django 6.0.5 on 2026-05-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
