# Generated by Django 6.0.5 on 2026-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_options_shipment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shipments/'),
        ),
    ]
